spring.application.name=Proyecto4
# Evitar que Spring Boot configure o inicie automáticamente una base de datos
spring.datasource.url=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true